# Generated by Django 2.2.7 on 2019-11-22 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Control',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.CharField(max_length=2000)),
                ('subject', models.CharField(max_length=2000)),
                ('date_start', models.DateTimeField()),
                ('date_end', models.DateTimeField()),
                ('status', models.IntegerField(choices=[(0, 'w przygotowaniu'), (1, 'w trakcie'), (2, 'zakończona')])),
                ('checklist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='controls', to='kontrolBack.Checklist')),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResultInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='kontrolBack.Control')),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='kontrolBack.ResultInfo')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, unique=True)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='questions', to='kontrolBack.QuestionBlock')),
            ],
        ),
        migrations.AddField(
            model_name='control',
            name='controlled_institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='controls_at', to='kontrolBack.Institution'),
        ),
        migrations.AddField(
            model_name='control',
            name='controlling_institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='controls_by', to='kontrolBack.Institution'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='questions',
            field=models.ManyToManyField(to='kontrolBack.Question'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='kontrolBack.Checklist')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='comments', to='kontrolBack.Question')),
            ],
            options={
                'unique_together': {('question', 'checklist')},
            },
        ),
    ]
