# Generated by Django 2.2.7 on 2019-11-26 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kontrolBack', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionInList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_name', models.CharField(max_length=500)),
                ('block_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='checklist',
            name='questions',
        ),
        migrations.AddField(
            model_name='checklist',
            name='name',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='comments', to='kontrolBack.QuestionInList'),
        ),
        migrations.AlterField(
            model_name='control',
            name='status',
            field=models.IntegerField(choices=[(0, 'w przygotowaniu'), (1, 'w trakcie'), (2, 'procedowanie uwag do wyniku'), (3, 'zakończona')], default=0),
        ),
        migrations.AddField(
            model_name='questioninlist',
            name='checklist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='kontrolBack.Checklist'),
        ),
        migrations.AddConstraint(
            model_name='questioninlist',
            constraint=models.UniqueConstraint(fields=('question_name', 'checklist'), name='dont_repeat_question_in_checklist'),
        ),
    ]
