# Generated by Django 2.2.7 on 2020-01-23 20:46

from django.db import migrations


INSTITUTIONS_STRING = """PLBU  >>> IZ.00.PLBU  >>> Ministerstwo Funduszy i Polityki Regionalnej, IZ PLBUNEWLINE
PLBU  >>> IP.01.PLBU  >>> Joint Technical Secretariat, PLBUNEWLINE
PLRU  >>> IZ.00.PLRU  >>> Ministerstwo Funduszy i Polityki Regionalnej, IZ PLRUNEWLINE
PLRU  >>> IP.01.PLRU  >>> Joint Technical Secretariat, PLRUNEWLINE
PLSK  >>> IZ.00.PLSK  >>> Ministerstwo Funduszy i Polityki Regionalnej, IZ PLSKNEWLINE
PLSK  >>> IP.01.PLSK  >>> Wspólny Sekretariat PLSKNEWLINE
PLSK  >>> IW.01.PLSK  >>> Małopolski Urząd WojewódzkiNEWLINE
PLSK  >>> IW.02.PLSK  >>> Podkarpacki Urząd WojewódzkiNEWLINE
PLSK  >>> IW.03.PLSK  >>> Śląski Urząd WojewódzkiNEWLINE
PLSN  >>> IZ.00.PLSN  >>> Ministerstwo Funduszy i Polityki Regionalnej, IZ PLSNNEWLINE
PLSN  >>> IP.01.PLSN  >>> Wspólny Sekretariat PLSNNEWLINE
PLSN  >>> IW.01.PLSN  >>> Dolnośląski Urząd WojewódzkiNEWLINE
PLSN  >>> IW.02.PLSN  >>> Lubuski Urząd WojewódzkiNEWLINE
POIR  >>> IZ.00.POIR  >>> Ministerstwo Funduszy i Polityki Regionalnej, IZ POIRNEWLINE
POIR  >>> IP.01.POIR  >>> Narodowe Centrum Badań i RozwojuNEWLINE
POIR  >>> IP.02.POIR  >>> Ministerstwo GospodarkiNEWLINE
POIR  >>> IP.03.POIR  >>> Polska Agencja Rozwoju PrzedsiębiorczościNEWLINE
POIR  >>> IP.04.POIR  >>> Bank Gospodarstwa KrajowegoNEWLINE
POIR  >>> IW.01.POIR  >>> Polska Agencja Rozwoju PrzedsiębiorczościNEWLINE
POIR  >>> IW.02.POIR  >>> Ośrodek Przetwarzania Informacji - Państwowy Instytut BadawczyNEWLINE
POIR  >>> IW.03.POIR  >>> Bank Gospodarstwa KrajowegoNEWLINE
POIR  >>> IW.04.POIR  >>> Fundacja na rzecz Nauki PolskiejNEWLINE
POIS  >>> IZ.00.POIS  >>> Ministerstwo Funduszy i Polityki Regionalnej, IZ POISNEWLINE
POIS  >>> IP.01.POIS  >>> Ministerstwo KlimatuNEWLINE
POIS  >>> IP.02.POIS  >>> Ministerstwo Aktywów PaństwowychNEWLINE
POIS  >>> IP.03.POIS  >>> Centrum Unijnych Projektów TransportowychNEWLINE
POIS  >>> IP.04.POIS  >>> Ministerstwo ZdrowiaNEWLINE
POIS  >>> IP.05.POIS  >>> Ministerstwo Kultury i Dziedzictwa NarodowegoNEWLINE
POIS  >>> IW.01.POIS  >>> Centrum Koordynacji Projektów ŚrodowiskowychNEWLINE
POIS  >>> IW.02.POIS  >>> Narodowy Fundusz Ochrony Środowiska i Gospodarki WodnejNEWLINE
POIS  >>> IW.04.POIS  >>> Wojewódzki Fundusz Ochrony Środowiska i Gospodarki Wodnej w KatowicachNEWLINE
POIS  >>> IW.05.POIS  >>> Instytut Nafty i Gazu - Państwowy Instytut BadawczyNEWLINE
POPC  >>> IZ.00.POPC  >>> Ministerstwo Funduszy i Polityki Regionalnej, IZ POPCNEWLINE
POPC  >>> IP.01.POPC  >>> Centrum Projektów Polska CyfrowaNEWLINE
POPT  >>> IZ.00.POPT  >>> Ministerstwo Funduszy i Polityki Regionalnej, DPTNEWLINE
POPW  >>> IZ.00.POPW  >>> Ministerstwo Funduszy i Polityki Regionalnej, IZ POPWNEWLINE
POPW  >>> IP.01.POPW  >>> Polska Agencja Rozwoju PrzedsiębiorczościNEWLINE
POPW  >>> IP.02.POPW  >>> Centrum Unijnych Projektów TransportowychNEWLINE
POWR  >>> IZ.00.POWR  >>> Ministerstwo Funduszy i Polityki Regionalnej, IZ POWRNEWLINE
POWR  >>> IP.01.POWR  >>> Ministerstwo Spraw Wewnętrznych i AdministracjiNEWLINE
POWR  >>> IP.02.POWR  >>> Ministerstwo Edukacji NarodowejNEWLINE
POWR  >>> IP.03.POWR  >>> Ministerstwo Rodziny, Pracy i Polityki SpołecznejNEWLINE
POWR  >>> IP.04.POWR  >>> Ministerstwo SprawiedliwościNEWLINE
POWR  >>> IP.05.POWR  >>> Ministerstwo ZdrowiaNEWLINE
POWR  >>> IP.06.POWR  >>> Kancelaria Prezesa Rady MinistrówNEWLINE
POWR  >>> IP.07.POWR  >>> Centrum Projektów EuropejskichNEWLINE
POWR  >>> IP.08.POWR  >>> Narodowe Centrum Badań i RozwojuNEWLINE
POWR  >>> IP.09.POWR  >>> Polska Agencja Rozwoju PrzedsiębiorczościNEWLINE
POWR  >>> IP.10.POWR  >>> Dolnośląski Wojewódzki Urząd PracyNEWLINE
POWR  >>> IP.11.POWR  >>> Wojewódzki Urząd Pracy w BiałymstokuNEWLINE
POWR  >>> IP.12.POWR  >>> Wojewódzki Urząd Pracy w GdańskuNEWLINE
POWR  >>> IP.13.POWR  >>> Wojewódzki Urząd Pracy w KatowicachNEWLINE
POWR  >>> IP.14.POWR  >>> Wojewódzki Urząd Pracy w KielcachNEWLINE
POWR  >>> IP.15.POWR  >>> Wojewódzki Urząd Pracy w KrakowieNEWLINE
POWR  >>> IP.16.POWR  >>> Wojewódzki Urząd Pracy w LublinieNEWLINE
POWR  >>> IP.17.POWR  >>> Wojewódzki Urząd Pracy w ŁodziNEWLINE
POWR  >>> IP.18.POWR  >>> Wojewódzki Urząd Pracy w OlsztynieNEWLINE
POWR  >>> IP.19.POWR  >>> Wojewódzki Urząd Pracy w OpoluNEWLINE
POWR  >>> IP.20.POWR  >>> Wojewódzki Urząd Pracy w PoznaniuNEWLINE
POWR  >>> IP.21.POWR  >>> Wojewódzki Urząd Pracy w RzeszowieNEWLINE
POWR  >>> IP.22.POWR  >>> Wojewódzki Urząd Pracy w SzczecinieNEWLINE
POWR  >>> IP.23.POWR  >>> Wojewódzki Urząd Pracy w ToruniuNEWLINE
POWR  >>> IP.24.POWR  >>> Wojewódzki Urząd Pracy w WarszawieNEWLINE
POWR  >>> IP.25.POWR  >>> Wojewódzki Urząd Pracy w Zielonej GórzeNEWLINE
RPDS  >>> IZ.00.RPDS  >>> Urząd Marszałkowski Województwa Dolnośląskiego, IZ RPDSNEWLINE
RPDS  >>> IP.01.RPDS  >>> Dolnośląska Instytucja PośredniczącaNEWLINE
RPDS  >>> IP.02.RPDS  >>> Dolnośląski Wojewódzki Urząd PracyNEWLINE
RPDS  >>> IP.03.RPDS  >>> Zintegrowane Inwestycje Terytorialne Aglomeracji WałbrzyskiejNEWLINE
RPKP  >>> IZ.00.RPKP  >>> Urząd Marszałkowski Województwa Kujawsko-Pomorskiego, IZ RPKPNEWLINE
RPKP  >>> IP.01.RPKP  >>> Wojewódzki Urząd Pracy w ToruniuNEWLINE
RPLB  >>> IZ.00.RPLB  >>> Urząd Marszałkowski Województwa Lubuskiego, IZ RPLBNEWLINE
RPLB  >>> IP.02.RPLB  >>> Wojewódzki Fundusz Ochrony Środowiska i Gospodarki Wodnej w Zielonej GórzeNEWLINE
RPLD  >>> IZ.00.RPLD  >>> Urząd Marszałkowski Województwa Łódzkiego, IZ RPLDNEWLINE
RPLD  >>> IP.01.RPLD  >>> Wojewódzki Urząd Pracy w ŁodziNEWLINE
RPLD  >>> IP.02.RPLD  >>> Centrum Obsługi PrzedsiębiorcyNEWLINE
RPLU  >>> IZ.00.RPLU  >>> Urząd Marszałkowski Województwa Lubelskiego, IZ RPLUNEWLINE
RPLU  >>> IP.01.RPLU  >>> Lubelska Agencja Wspierania Przedsiębiorczości w LublinieNEWLINE
RPLU  >>> IP.02.RPLU  >>> Wojewódzki Urząd Pracy w LublinieNEWLINE
RPMA  >>> IZ.00.RPMA  >>> Urząd Marszałkowski Województwa Mazowieckiego, IZ RPMANEWLINE
RPMA  >>> IP.01.RPMA  >>> Mazowiecka Jednostka Wdrażania Programów UnijnychNEWLINE
RPMA  >>> IP.02.RPMA  >>> Wojewódzki Urząd Pracy w WarszawieNEWLINE
RPMA  >>> IP.03.RPMA  >>> Urząd m.st WarszawyNEWLINE
RPMP  >>> IZ.00.RPMP  >>> Urząd Marszałkowski Województwa Małopolskiego, IZ RPMPNEWLINE
RPMP  >>> IP.01.RPMP  >>> Małopolskie Centrum PrzedsiębiorczościNEWLINE
RPMP  >>> IP.02.RPMP  >>> Wojewódzki Urząd Pracy w KrakowieNEWLINE
RPMP  >>> IP.03.RPMP  >>> Stowarzyszenie Metropolia KrakowskaNEWLINE
RPOP  >>> IZ.00.RPOP  >>> Urząd Marszałkowski Województwa Opolskiego, IZ RPOPNEWLINE
RPOP  >>> IP.01.RPOP  >>> Opolskie Centrum Rozwoju GospodarkiNEWLINE
RPOP  >>> IP.02.RPOP  >>> Wojewódzki Urząd Pracy w OpoluNEWLINE
RPOP  >>> IP.03.RPOP  >>> Aglomeracja OpolskaNEWLINE
RPPD  >>> IZ.00.RPPD  >>> Urząd Marszałkowski Województwa Podlaskiego, IZ RPPDNEWLINE
RPPD  >>> IP.01.RPPD  >>> Wojewódzki Urząd Pracy w BiałymstokuNEWLINE
RPPK  >>> IZ.00.RPPK  >>> Urząd Marszałkowski Województwa Podkarpackiego, IZ RPPKNEWLINE
RPPK  >>> IP.01.RPPK  >>> Wojewódzki Urząd Pracy w RzeszowieNEWLINE
RPPK  >>> IP.02.RPPK  >>> Stowarzyszenie Rzeszowskiego Obszaru FunkcjonalnegoNEWLINE
RPPM  >>> IZ.00.RPPM  >>> Urząd Marszałkowski Województwa Pomorskiego, IZ RPPMNEWLINE
RPPM  >>> IP.01.RPPM  >>> Wojewódzki Urząd Pracy w GdańskuNEWLINE
RPPM  >>> IP.02.RPPM  >>> Agencja Rozwoju Pomorza S.A.NEWLINE
RPSL  >>> IZ.01.RPSL  >>> Urząd Marszałkowski Województwa Śląskiego, IZ RPSLNEWLINE
RPSL  >>> IP.01.RPSL  >>> Śląskie Centrum PrzedsiębiorczościNEWLINE
RPSL  >>> IP.02.RPSL  >>> Wojewódzki Urząd Pracy w KatowicachNEWLINE
RPSW  >>> IZ.00.RPSW  >>> Urząd Marszałkowski Województwa Świętokrzyskiego, IZ RPSWNEWLINE
RPSW  >>> IP.01.RPSW  >>> Wojewódzki Urząd Pracy w KielcachNEWLINE
RPSW  >>> IP.02.RPSW  >>> Urząd Miasta KielceNEWLINE
RPWM  >>> IZ.00.RPWM  >>> Urząd Marszałkowski Województwa Warmińsko-Mazurskiego, IZ RPWMNEWLINE
RPWM  >>> IP.01.RPWM  >>> Wojewódzki Urząd Pracy w OlsztynieNEWLINE
RPWM  >>> IP.02.RPWM  >>> Wojewódzki Fundusz Ochrony Środowiska i Gospodarki Wodnej w OlsztynieNEWLINE
RPWM  >>> IP.03.RPWM  >>> WMARR S.A.NEWLINE
RPWP  >>> IZ.00.RPWP  >>> Urząd Marszałkowski Województwa Wielkopolskiego, IZ RPWPNEWLINE
RPWP  >>> IP.03.RPWP  >>> Wojewódzki Urząd Pracy w PoznaniuNEWLINE
RPZP  >>> IZ.00.RPZP  >>> Urząd Marszałkowski Województwa Zachodniopomorskiego, IZ RPZPNEWLINE
RPZP  >>> IP.02.RPZP  >>> Wojewódzki Urząd Pracy w SzczecinieNEWLINE
STHB  >>> IZ.00.STHB  >>> Ministerstwo Funduszy i Polityki Regionalnej, IZ STHBNEWLINE
STHB  >>> IP.01.STHB  >>> Wspólny Sekretariat STHBNEWLINE
STHB  >>> IW.01.STHB  >>> Pomorski Urząd WojewódzkiNEWLINE
STHB  >>> IW.02.STHB  >>> Warmińsko-Mazurski Urząd WojewódzkiNEWLINE
STHB  >>> IW.03.STHB  >>> Zachodniopomorski Urząd WojewódzkiNEWLINE\n"""


def create_institutions(apps, schema_editor):
    Institution = apps.get_model('kontrolBack', 'Institution')
    records = [inner.split(' >>> ') for inner in INSTITUTIONS_STRING.split('NEWLINE\n')][:-1]
    institutions = [Institution(programme=r[0], code=r[1], name=r[2]) for r in records]  
    Institution.objects.bulk_create(institutions)


class Migration(migrations.Migration):

    dependencies = [
        ('kontrolBack', '0002_questioninlist_checklist'),
    ]

    operations = [
        migrations.RunPython(create_institutions)
    ]
