# Generated by Django 2.2.7 on 2019-12-05 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kontrolBack', '0002_auto_20191126_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
