# Generated by Django 2.2.7 on 2019-12-12 21:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kontrolBack', '0003_checklist_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectParticipant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
            ],
        ),
        migrations.RenameField(
            model_name='control',
            old_name='controlling_institution',
            new_name='controlling',
        ),
        migrations.RenameField(
            model_name='control',
            old_name='goal',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='control',
            name='controlled_institution',
        ),
        migrations.AddField(
            model_name='recommendation',
            name='content',
            field=models.CharField(default='default recommendatioon', max_length=10000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='control',
            name='status',
            field=models.IntegerField(choices=[(0, 'w przygotowaniu'), (1, 'w trakcie'), (2, 'w procesie zgłaszania uwag do wyniku'), (3, 'zakończona')], default=0),
        ),
        migrations.AlterField(
            model_name='institution',
            name='name',
            field=models.CharField(max_length=512, unique=True),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='result_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recommendations', to='kontrolBack.ResultInfo'),
        ),
        migrations.AlterField(
            model_name='resultinfo',
            name='control',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='kontrolBack.Control'),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('value', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('description', models.CharField(max_length=3000, null=True)),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects_as_benef', to='kontrolBack.ProjectParticipant')),
                ('partners', models.ManyToManyField(related_name='projects_as_partner', to='kontrolBack.ProjectParticipant')),
            ],
        ),
        migrations.CreateModel(
            name='InstitutionEmployee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kontrolBack.Institution')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=10000)),
                ('result_info', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='findings', to='kontrolBack.ResultInfo')),
            ],
        ),
        migrations.AddField(
            model_name='control',
            name='controlled',
            field=models.ManyToManyField(related_name='controls_at', to='kontrolBack.ProjectParticipant'),
        ),
    ]
