# Generated by Django 2.2.7 on 2019-12-13 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kontrolBack', '0004_auto_20191212_2154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='control',
            name='controlled',
        ),
        migrations.AddField(
            model_name='control',
            name='controlled',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='controls_at', to='kontrolBack.ProjectParticipant'),
            preserve_default=False,
        ),
    ]
