# Generated by Django 2.2.7 on 2019-12-14 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kontrolBack', '0005_auto_20191213_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='questioninlist',
            name='answer',
            field=models.IntegerField(choices=[(0, 'tak'), (1, 'nie'), (2, 'nie dotyczy')], null=True),
        ),
    ]
