# Generated by Django 2.2.7 on 2019-12-14 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kontrolBack', '0006_questioninlist_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='control',
            name='project',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='controls_at_project', to='kontrolBack.Project'),
        ),
        migrations.AlterField(
            model_name='control',
            name='controlled',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='controls_at_participant', to='kontrolBack.ProjectParticipant'),
        ),
    ]
