# Generated by Django 2.2.7 on 2019-12-14 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kontrolBack', '0007_auto_20191214_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='control',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='controls_at_project', to='kontrolBack.Project'),
        ),
    ]
