# Generated by Django 2.2.7 on 2020-01-25 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kontrolBack', '0007_auto_20200125_0858'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionInControl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_name', models.CharField(max_length=500)),
                ('block_name', models.CharField(max_length=255)),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='kontrolBack.Control')),
            ],
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kontrolBack.QuestionInControl'),
        ),
    ]
