# Generated by Django 2.2.7 on 2019-12-14 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kontrolBack', '0008_auto_20191214_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='control',
            name='project',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
