# Generated by Django 2.2.7 on 2019-12-15 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kontrolBack', '0009_auto_20191214_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='code',
            field=models.CharField(max_length=512, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='control',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='controls_at_project', to='kontrolBack.Project'),
            preserve_default=False,
        ),
    ]
