# Generated by Django 2.2.7 on 2020-01-26 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kontrolBack', '0010_auto_20200126_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='comment',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
