# Generated by Django 2.2.7 on 2020-02-02 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kontrolBack', '0012_auto_20200126_1704'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name_plural': 'pytania'},
        ),
        migrations.AlterField(
            model_name='checklist',
            name='name',
            field=models.CharField(max_length=255, verbose_name='nazwa'),
        ),
        migrations.AlterField(
            model_name='control',
            name='checklist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='controls', to='kontrolBack.Checklist', verbose_name='lista sprawdzająca'),
        ),
        migrations.AlterField(
            model_name='control',
            name='controlling',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='controls_by', to='kontrolBack.Institution', verbose_name='instytucja kontrolująca'),
        ),
        migrations.AlterField(
            model_name='control',
            name='date_end',
            field=models.DateTimeField(verbose_name='koniec'),
        ),
        migrations.AlterField(
            model_name='control',
            name='date_start',
            field=models.DateTimeField(verbose_name='początek'),
        ),
        migrations.AlterField(
            model_name='control',
            name='name',
            field=models.CharField(max_length=2000, verbose_name='nazwa'),
        ),
        migrations.AlterField(
            model_name='control',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='controls_at_project', to='kontrolBack.Project', verbose_name='projekt'),
        ),
        migrations.AlterField(
            model_name='questionblock',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='blok'),
        ),
    ]
