# Generated by Django 2.2.7 on 2020-02-02 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kontrolBack', '0013_auto_20200202_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='comment',
            field=models.CharField(blank=True, max_length=10000, null=True, verbose_name='komentarz'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='content',
            field=models.IntegerField(choices=[(0, 'tak'), (1, 'nie'), (2, 'nie dotyczy')], verbose_name='odpowiedź'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='kontrolBack.QuestionInControl', verbose_name='pytanie'),
        ),
    ]
