# Generated by Django 2.2.7 on 2020-01-24 20:17

from django.db import migrations


PROJECTS_STRING = """POIR  >>> POIR.01.01.01-00-0002/17  >>> Mobilna linia przetwarzania odpadów komunalnych-rezultatem badań przemysłowych i prac rozwojowych  >>> PRONAR SPÓŁKA Z OGRANICZONĄ ODPOWIEDZIALNOŚCIĄ  >>> 5430200939NEWLINE
POIR  >>> POIR.01.01.01-00-0003/19  >>> Platforama Business Intelligence firmy SESCOM do inteligentnego zarzadzania nieruchomościami i oszczędzania energii  >>> SESCOM SPÓŁKA AKCYJNA  >>> 9571006288NEWLINE
POIR  >>> POIR.01.01.01-00-0004/15  >>> Opracowanie technologii produkcji jonowych farb higienicznych GALVI z mikroogniwami galwanicznymi dla biokontroli zakażeń grzybiczych wewnątrz budowli.  >>> CENTRUM BADAWCZO-PRODUKCYJNE ALCOR SP. Z O.O.  >>> 7540337882NEWLINE
POIR  >>> POIR.01.01.01-00-0005/15  >>> Prace badawcze metodami DEM i CFD nad nowymi materiałami i technologiami w produkcji materiałów budowlanych  >>> BIKO-SERWIS SP. Z O.O. SP.K.  >>> 6561002324NEWLINE
POIR  >>> POIR.01.01.01-00-0005/17  >>> Uzyskanie nowych odmian maliny czarnej w procesie hodowli twórczej oraz opracowanie technologii dla ukierunkowanej produkcji owoców  >>> NIWA HODOWLA ROŚLIN JAGODOWYCH SPÓŁKA Z OGRANICZONĄ ODPOWIEDZIALNOŚCIĄ  >>> 7343515776NEWLINE
POIR  >>> POIR.01.01.01-00-0006/16  >>> Narzędzia wykorzystujące nowatorskie metody: okulograficzną, elektrofizjologiczną i introspekcję – automatyzujące analizę preferencji klientów oraz kontrolę jakości produkcji filmów i gier komputerowych.  >>> FUNDACJA ISYRIUS  >>> 7292701255NEWLINE
POIR  >>> POIR.01.01.01-00-0006/17  >>> Innowacyjny opryskiwacz dwuwentylatorowy z asymetryczną regulacją strumienia powietrza  >>> NIEGOWSKI ZDZISŁAW "AGROLA" ZAKŁAD HANDLOWO-PRODUKCYJNY  >>> 8240001061NEWLINE
POIR  >>> POIR.01.01.01-00-0007/19  >>> Specjalistyczny kombajn do wielokrotnego zbioru owoców borówki wysokiej  >>> JAGODA JPS MAGDALENA PLACEK BASEL SARAYA SPÓŁKA CYWILNA  >>> 8361396940NEWLINE
POIR  >>> POIR.01.01.01-00-0008/15  >>> Innowacyjny, wielomodułowy, konwertowany wiropłat dwusilnikowy  >>> FUSIONCOPTER SP. Z O.O.  >>> 9512355053NEWLINE
POIR  >>> POIR.01.01.01-00-0009/16  >>> Prace badawczo-rozwojowe nad opracowaniem i wdrożeniem innowacyjnej technologii obróbki mechanicznej korpusu silników elektrycznych z zastosowaniem narzędzi specjalnych, wyposażonych w tłumik drgań.  >>> FERRPOL BRACIA MATUSZEWSCY SP. Z O.O.  >>> 6991832330NEWLINE
POIR  >>> POIR.01.01.01-00-0009/17  >>> Opracowanie technologii odzysku łupków przywęglowych do jednoczesnej produkcji metakaolinu i kruszyw drogowo-budowlanych z dodatkowym odzyskiem energii  >>> FABRYKA CERAMIKI BUDOWLANEJ RONENBERGER LTD TOMASZ RONCZOSZEK  >>> 6451035699NEWLINE
POIR  >>> POIR.01.01.01-00-0009/19  >>> Opracowanie systemu informatycznego opartego m.in. na technologii uczenia maszynowego, wspierającego małe i średnie przedsiębiorstwa w sprzedaży ich produktów na międzynarodowych platformach e-commerce (tzw. marketplace&rsquo;ach)  >>> ODC GROUP SPÓŁKA Z OGRANICZONĄ ODPOWIEDZIALNOŚCIĄ SPÓŁKA KOMANDYTOWA  >>> 1132879484NEWLINE
POWR  >>> POWR.01.02.01-12-0141/19  >>> Z POWERem - WSPARCIE NA STARCIE!  >>> JMM MARIUSZ LEWANDOWSKI  >>> 8211060291NEWLINE
POWR  >>> POWR.01.02.01-12-0142/19  >>> Z POWER-em w życie  >>> FUNDACJA IM. HETMANA JANA TARNOWSKIEGO  >>> 8732676391NEWLINE
POWR  >>> POWR.01.02.01-14-0004/19  >>> Młodzi Aktywni na Mazowszu  >>> MDDP SPÓŁKA AKCYJNA AKADEMIA BIZNESU SP. K.  >>> 7010088170NEWLINE
POWR  >>> POWR.01.02.01-14-0006/18  >>> Akcja aktywizacja!  >>> VISION CONSULTING SPÓŁKA Z OGRANICZONĄ ODPOWIEDZIALNOŚCIĄ  >>> 6762411816NEWLINE
POWR  >>> POWR.01.02.01-14-0008/18  >>> Młodzieżowe wyzwania zawodowe  >>> J&C GROUP KAROLINA CHADZYPANAGIOTIS-JURKIEWICZ  >>> 5862057791NEWLINE
POWR  >>> POWR.01.02.01-14-0008/19  >>> Młodzi aktywni na rynku pracy  >>> TOMASZ ŻUREK INFOS  >>> 7642093946NEWLINE
POWR  >>> POWR.01.02.01-14-0010/18  >>> Warszawskie Centrum Animacji Kariery Osób Młodych.  >>> FUNDACJA SUSTINAE  >>> 6762457416NEWLINE
POWR  >>> POWR.01.02.01-14-0011/15  >>> Powrót młodzieży NEET na rynek pracy  >>> LUBELSKA SZKOŁA BIZNESU SP. Z O.O. FUNDACJI ROZWOJU KUL  >>> 7120152288NEWLINE
POWR  >>> POWR.01.02.01-14-0015/18  >>> Mazowsze z POWERem!  >>> VIVID CONSULTING SPÓŁKA Z OGRANICZONĄ ODPOWIEDZIALNOŚCIĄ  >>> 8951963618NEWLINE
POWR  >>> POWR.01.02.01-14-0015/19  >>> Aktywna młodzież!  >>> PLUSK POLSKA SP.ZO.O.SP.K.  >>> 5270103333NEWLINE
POWR  >>> POWR.01.02.01-14-0019/18  >>> Zaprojektuj sukces zawodowy z POWEREM  >>> FUNDACJA NA RZECZ INTEGRACJI ZAWODOWEJ, SPOŁECZNEJ ORAZ ROZWOJU PRZEDSIĘBIORCZOŚCI VIA  >>> 5252331354NEWLINE
POWR  >>> POWR.01.02.01-14-0021/18  >>> Skuteczni na rynku pracy  >>> FUNDACJA "ECO"  >>> 9462638575NEWLINE
POWR  >>> POWR.01.02.01-14-0023/19  >>> Młodzi Liderzy Sukcesu !  >>> KS CONSULTING SPÓŁKA Z OGRANICZONĄ ODPOWIEDZIALNOŚCIĄ  >>> 9512433534NEWLINE
POWR  >>> POWR.01.02.01-14-0026/18  >>> Wsparcie na starcie! Indywidualna i kompleksowa pomoc w wejściu na rynek pracy osób młodych zamieszkujących powiat ostrołęcki i miasto Ostrołęka.  >>> JOLANTA WOŹNICA "PERSONA" OŚRODEK SZKOLENIOWO-DORADCZY  >>> 5561051693NEWLINE
POWR  >>> POWR.01.02.01-14-0030/18  >>> Kompleksowe wsparcie osób młodych Neet z terenu Mazowsza  >>> ZAKŁAD DOSKONALENIA ZAWODOWEGO W PŁOCKU  >>> 7741079234NEWLINE
POWR  >>> POWR.01.02.01-14-0030/19  >>> Nowe możliwości - lepsza praca  >>> AKADEMICKIE STOWARZYSZENIE INICJATYW SPOŁECZNO-EDUKACYJNYCH  >>> 7122832136NEWLINE
POWR  >>> POWR.01.02.01-14-0031/18  >>> Aktywna przyszłość. Program aktywizacji zawodowo-edukacyjnej osób z niepełnosprawnościami w wieku 18-29 r.ż. z województwa mazowieckiego  >>> POLSKI HR - A-TRYBUT SPÓŁKA AKCYJNA  >>> 6762455357NEWLINE
POWR  >>> POWR.01.02.01-14-0031/19  >>> Mazowiecki Akcelerator Startu Zawodowego  >>> CERTES SP. Z O.O.  >>> 5213445303NEWLINE
POWR  >>> POWR.01.02.01-14-0032/18  >>> Obierz kurs na przyszłość II - aktywizacja osób młodych  >>> TOWARZYSTWO ALTUM PROGRAMY SPOŁECZNO-GOSPODARCZE  >>> 8131086874NEWLINE
POWR  >>> POWR.01.02.01-14-0033/18  >>> Otwarty katalog możliwości  >>> KAMEA PAWEŁ KOZARZEWSKI  >>> 7122603708NEWLINE
POWR  >>> POWR.01.02.01-14-0034/15  >>> Rozwój - praca - szanse na rynku pracy  >>> T-MATIC GRUPA COMPUTER PLUS SP. Z O.O.  >>> 5420201630NEWLINE
POWR  >>> POWR.01.02.01-14-0034/18  >>> Młodość kluczem sukcesu !  >>> INSPIRES SP. Z O.O.  >>> 7142044672NEWLINE
POWR  >>> POWR.01.02.01-14-0036/16  >>> Postaw na rozwój!  >>> WIELKOPOLSKIE STOWARZYSZENIE NA RZECZ ROZWOJU OBSZARÓW WIEJSKICH  >>> 7891577442NEWLINE
POWR  >>> POWR.01.02.01-14-0036/18  >>> Młodzi-->kompetentni-->wykwalifikowani  >>> TOMASZ ŻUREK INFOS  >>> 7642093946NEWLINE
POWR  >>> POWR.01.02.01-14-0037/18  >>> Mazowieckie CENTRUM ROZWOJU Zawodowego NEET  >>> CENTRUM ROZWOJU SPOŁECZNO-EKONOMICZNEGO  >>> 8181528535NEWLINE
POWR  >>> POWR.01.02.01-14-0039/18  >>> Twoja ścieżka kariery!  >>> EURO-EDUKATOR EWA KANABUS-KOSZAL  >>> 1230280601NEWLINE
POWR  >>> POWR.01.02.01-14-0045/18  >>> Czas na zmianę - II edycja  >>> LUBELSKI OŚRODEK SAMOPOMOCY  >>> 7122392619NEWLINE
POWR  >>> POWR.01.02.01-14-0047/15  >>> Kurs Kierowcy  >>> AKADEMICKIE STOWARZYSZENIE INICJATYW SPOŁECZNO-EDUKACYJNYCH  >>> 7122832136NEWLINE
POWR  >>> POWR.01.02.01-14-0051/18  >>> Aktywizujemy młodych  >>> STOWARZYSZENIE AKTYWNEGO WSPIERANIA GOSPODARKI  >>> 8992670534NEWLINE
POWR  >>> POWR.01.02.01-14-0052/15  >>> Droga na rynek pracy  >>> "DORADZTWO PERSONALNE SET" SZTOMBERSKA-EJDYS TERESA CENTRUM POMOCY PSYCHOLOGICZNEJ  >>> 7741940817NEWLINE
POWR  >>> POWR.01.02.01-14-0052/19  >>> Zdobądź lepszą pracę dzięki ZDZ w Płocku !  >>> ZAKŁAD DOSKONALENIA ZAWODOWEGO W PŁOCKU  >>> 7741079234NEWLINE
POWR  >>> POWR.01.02.01-14-0053/18  >>> Twoja szansa!  >>> FUNDACJA MOŻESZ WIĘCEJ  >>> 6572907626NEWLINE
POWR  >>> POWR.01.02.01-14-0054/15  >>> Wsparcie osób młodych  >>> MDDP SPÓŁKA Z OGRANICZONĄ ODPOWIEDZIALNOŚCIĄ AKADEMIA BIZNESU SP. K.  >>> 7010088170NEWLINE
POWR  >>> POWR.01.02.01-14-0055/18  >>> Młodzi gotowi do działania!  >>> PLUSK POLSKA SP.ZO.O.SP.K.  >>> 5270103333NEWLINE
POWR  >>> POWR.01.02.01-14-0056/15  >>> Opiekunka domowa seniora  >>> OPTIMA HRS KINGA KORONKIEWICZ  >>> 8451696255NEWLINE
POWR  >>> POWR.01.02.01-14-0057/18  >>> Stawiamy na młodych!  >>> CONSULTOR SPÓŁKA Z OGRANICZONĄ ODPOWIEDZIALNOŚCIĄ  >>> 7120162803NEWLINE
POWR  >>> POWR.01.02.01-14-0062/18  >>> Zaprojektuj karierę z POWEREM  >>> FUNDACJA MAMY PRAWA  >>> 5272688148NEWLINE
POWR  >>> POWR.01.02.01-14-0065/18  >>> Możliwości dla młodych  >>> PRZEDSIĘBIORSTWO PRODUKCYJNO USŁUGOWO SZKOLENIOWE "KMP" MARCIN PIOTROWSKI  >>> 7991724380NEWLINE
POWR  >>> POWR.01.02.01-14-0066/15  >>> Warszawa bez ograniczeń  >>> GDELA KRYSTYNA AKUSTICA.MED  >>> 5371259002NEWLINE
POWR  >>> POWR.01.02.01-14-0066/18  >>> Krok do aktywności  >>> WIELKOPOLSKIE STOWARZYSZENIE NA RZECZ ROZWOJU OBSZARÓW WIEJSKICH  >>> 7891577442NEWLINE
POWR  >>> POWR.01.02.01-14-0067/18  >>> POWER - moja szansa!  >>> INVENTUM SPÓŁKA Z OGRANICZONĄ ODPOWIEDZIALNOŚCIĄ  >>> 7343518993NEWLINE
POWR  >>> POWR.01.02.01-14-0068/18  >>> Zawodowa przyszłość!  >>> INSTYTUT ORGANIZACJI PRZEDSIĘBIORSTW I TECHNIK INFORMACYJNYCH INBIT SP. Z O.O.  >>> 8512428946NEWLINE
POWR  >>> POWR.01.02.01-14-0068/19  >>> Młodzi na mazowieckim rynku pracy  >>> S.T.R. PROJECT STANISŁAW ROMANISZYN  >>> 7642624154NEWLINE
RPDS  >>> RPDS.10.03.00-02-0006/16  >>> Nowe kompetencje - nowe szanse.  >>> WITOLD SZASZKIEWICZ CENTRUM EDUKACYJNE "IDEA"  >>> 9441375254NEWLINE
RPDS  >>> RPDS.10.03.00-02-0007/16  >>> Dolnośląska Akademia ICT  >>> EGZAM S.C. HUBERT CYTAWA, ANNA KOTŁOWSKA  >>> 7123287563NEWLINE
RPDS  >>> RPDS.10.03.00-02-0013/16  >>> Komputer na wsi - rozwój kompetencji informatycznych mieszkańców Dolnego Śląska  >>> "ETURIA" SPÓŁKA Z OGRANICZONĄ ODPOWIEDZIALNOŚCIĄ  >>> 6793025072NEWLINE
RPDS  >>> RPDS.10.03.00-02-0014/17  >>> Znajomość języków i obsługi komputera furtką do większych szans na rynku pracy  >>> "SEVERN" SPÓŁKA Z OGRANICZONĄ ODPOWIEDZIALNOŚCIĄ  >>> 7010444682NEWLINE
RPDS  >>> RPDS.10.03.00-02-0019/16  >>> Akademia języków obcych  >>> ADVANCE EWELINA PODZIOMEK  >>> 5782574679NEWLINE
RPDS  >>> RPDS.10.03.00-02-0024/16  >>> English and Computers  >>> FUNDACJA SYCHEM  >>> 8822117086NEWLINE
RPDS  >>> RPDS.10.03.00-02-0031/16  >>> Szansa na przyszłość  >>> FUNDACJA "NASZE LEPSZE JUTRO"  >>> 8831857291NEWLINE
RPDS  >>> RPDS.10.03.00-02-0034/16  >>> Wiedza otwiera nowe horyzonty.  >>> POWIAT JAWORSKI  >>> 6951351475NEWLINE
RPDS  >>> RPDS.10.03.00-02-0034/17  >>> Szkoła kompetencji językowych i komputerowych  >>> IT RENT MARCIN TRZCIŃSKI  >>> 1181896761NEWLINE
RPDS  >>> RPDS.10.03.00-02-0037/17  >>> Level Up - kompleksowy program nabywania kompetencji językowych i cyfrowych mieszkańców ziemi dzierżoniowsko- kłodzko- ząbkowickiej  >>> STOWARZYSZENIE EURO-CONCRET  >>> 8942753436NEWLINE
RPDS  >>> RPDS.10.03.00-02-0038/17  >>> Altair 2018 - kompleksowy projekt nabywania umiejętności językowych i cyfrowych mieszkańców subregionu ZIT Aglomeracji Wałbrzyskiej  >>> "POLSKA IZBA MŁODYCH PRZEDSIĘBIORCÓW"  >>> 8951840790NEWLINE
RPDS  >>> RPDS.10.03.00-02-0041/16  >>> Język angielski kluczem do sukcesu  >>> COMMA PIOTR UJMA  >>> 9490137106NEWLINE
RPDS  >>> RPDS.10.03.00-02-0043/16  >>> Akademia Poligloty  >>> USŁUGI PODATKOWO-KSIĘGOWE BEATA KOBUS  >>> 5621033085NEWLINE
RPDS  >>> RPDS.10.03.00-02-0046/17  >>> Język obcy szansa na lepsze zatrudnienie! Edycja druga  >>> "THAMES SPÓŁKA Z OGRANICZONĄ ODPOWIEDZIALNOŚCIĄ"  >>> 5242776379NEWLINE
RPDS  >>> RPDS.10.03.00-02-0048/17  >>> Kwalifikacje godne Zachodu  >>> MOVERNO TOMASZ MIELCAREK  >>> 7791917737NEWLINE
RPDS  >>> RPDS.10.03.00-02-0053/17  >>> Po kwalifikacje  >>> DORADZTWO PERSONALNE I SZKOLENIA ALEKSANDRA ZAKRZEWSKA  >>> 6791708482NEWLINE
RPDS  >>> RPDS.10.03.00-02-0064/16  >>> Język angielski i komputer - mówię i rozumiem!  >>> STOWARZYSZENIE ,,WOLNA PRZEDSIĘBIORCZOŚĆ" ODDZIAŁ TERENOWY W GDAŃSK  >>> 5831020427NEWLINE
RPDS  >>> RPDS.10.03.00-02-0079/16  >>> Moc cyfrowych kompetencji  >>> NESTOR GROUP BARTOSZ BERKOWSKI  >>> 8981961506NEWLINE
RPDS  >>> RPDS.10.03.00-02-0081/16  >>> OK - Ośrodek Kompetencji Cyfrowych  >>> WWS DANIEL WIJAS  >>> 8861859521NEWLINE
RPDS  >>> RPDS.10.03.00-02-0083/16  >>> Po 50 roku życia klikanie? Z nami to nie jest wielkie wyzwanie!  >>> ICT ARTUR OLESIŃSKI  >>> 1181817371NEWLINE
RPDS  >>> RPDS.10.03.00-02-0103/16  >>> Kurs języka angielskiego dla początkujących  >>> „PRETENDER” ADRIAN WRONKA  >>> 7282625587NEWLINE
RPDS  >>> RPDS.10.03.00-02-0111/16  >>> Zdobądź kwalifikacje z języka niemieckiego  >>> TAG-CONSULTING MARTA MACIEJAK-TOMCZYK  >>> 8341587890NEWLINE
RPDS  >>> RPDS.10.03.00-02-0119/16  >>> Dolnośląska Akademia Umiejętności Językowych i Komputerowych  >>> MDDP SPÓŁKA Z OGRANICZONĄ ODPOWIEDZIALNOŚCIĄ AKADEMIA BIZNESU SP. K  >>> 7010088170NEWLINE
RPDS  >>> RPDS.10.03.00-02-0130/16  >>> Zdobądź e-umiejętności, poznaj nowe możliwości  >>> "INSTYTUT SZKOLEŃ INNOVUM" D.DIDIUK I M.WASILEWSKI SPÓŁKA JAWNA  >>> 1132772728NEWLINE
RPDS  >>> RPDS.10.03.00-02-0137/16  >>> Bliżej Europy - kompetencje językowe mieszkańców Dolnego Śląska  >>> OŚRODEK SZKOLENIA DOKSZTAŁCANIA I DOSKONALENIA KADR "KURSOR"  >>> 7120061775NEWLINE
RPDS  >>> RPDS.10.03.00-02-0140/16  >>> Dolnośląska Akademia Językowa  >>> EURO-FORUM MAREK GUDKÓW  >>> 9461233250NEWLINE
RPDS  >>> RPDS.10.03.00-02-0141/16  >>> Europejska Akademia Językowa - język angielski i niemiecki  >>> AST CONSULTING ALDONA SIKORA-TYMA  >>> 6681700321NEWLINE
RPDS  >>> RPDS.10.03.00-02-0142/16  >>> Język i komputery-DOLNOŚLĄSKIE STERY!  >>> OPEN EDUCATION GROUP SPÓŁKA Z OGRANICZONĄ ODPOWIEDZIALNOŚCIĄ  >>> 9661811272NEWLINE
RPDS  >>> RPDS.10.03.00-02-0144/16  >>> Języki i komputery przepustką do kariery!  >>> FUNDACJA INSTYTUT ROZWOJU ZASOBÓW LUDZKICH  >>> 7122764707NEWLINE
RPDS  >>> RPDS.10.03.00-02-0153/16  >>> Prosta sprawa - kompetencje to podstawa!  >>> GDELA KRYSTYNA AKUSTICA.MED  >>> 5371259002NEWLINE
RPDS  >>> RPDS.10.03.00-02-0156/16  >>> TIK tak - na kompetencje cyfrowe przychodzi czas!  >>> HUMANEO  >>> 7343157319NEWLINE
RPDS  >>> RPDS.10.03.00-02-0181/16  >>> Języki Branżowe i Umiejętności Cyfrowe Dla Mieszkańców Dolnego Śląska  >>> FUNDACJA RAZEM  >>> 8862772667NEWLINE
RPDS  >>> RPDS.10.03.00-02-0182/16  >>> Języki obce przepustką do kariery  >>> HUMAN POWER SPÓŁKA Z OGRANICZONĄ ODPOWIEDZIALNOŚCIĄ  >>> 5242627395NEWLINE
RPDS  >>> RPDS.10.03.00-02-0185/16  >>> Kompetencje z języka angielskiego sposobem na współczesny rynek pracy.  >>> ŚWIAT JĘZYKÓW - SZKOŁA JĘZYKÓW OBCYCH - SPÓŁKA CYWILNA MAŁGORZATA ŁUCZAK KRZYSZTOF GÓRCZYŃSKI  >>> 8262032778NEWLINE
RPDS  >>> RPDS.10.03.00-02-0192/16  >>> Szkolenia Językowe Twoją Szansą II  >>> PROFUTURA GROUP SPÓŁKA Z OGRANICZONĄ ODPOWIEDZIALNOŚCIĄ SPÓŁKA KOMANDYTOWA  >>> 7781443083NEWLINE
RPDS  >>> RPDS.10.03.00-02-0207/16  >>> Dolnośląska Akademia Kompetencji ICT  >>> FUNDACJA MAMY PRAWA  >>> 5272688148NEWLINE
RPDS  >>> RPDS.10.03.00-02-0208/16  >>> Mistrzowie klawiatury - bezpłatne szkolenia ICT dla dorosłych  >>> "EKSPERT" S.C. OWCZAREK ROBERT, HODORSKI PAWEŁ  >>> 5321775888NEWLINE
RPDS  >>> RPDS.10.03.00-02-0211/16  >>> TIK na tak! Szkolenia komputerowe dla dorosłych  >>> LEON EDUKATOR SPÓŁKA Z OGRANICZONĄ ODPOWIEDZIALNOŚCIĄ  >>> 5222961599NEWLINE
RPDS  >>> RPDS.10.03.00-02-0214/16  >>> Zdobądź e-umiejętności, zyskaj nowe możliwości  >>> TRUSTCON SPÓŁKA Z OGRANICZONĄ ODPOWIEDZIALNOŚCIĄ  >>> 5272596541NEWLINE
RPDS  >>> RPDS.10.03.00-02-0230/16  >>> Akademia języka niemieckiego  >>> WALL STREET BROKERS TOMASZ MARZEC  >>> 9452077419NEWLINE
RPDS  >>> RPDS.10.03.00-02-0247/16  >>> KomITywa 2016  >>> FUNDACJA WSPIERANIA ORGANIZACJI POZARZĄDOWYCH UMBRELLA  >>> 8982115162NEWLINE
RPDS  >>> RPDS.10.03.00-02-0249/16  >>> Zaprzyjaźnij się z TIK!  >>> IT7 KRZYSZTOF BOŻEK SZKOLENIA - USŁUGI INFORMATYCZNE  >>> 8941305629NEWLINE
RPDS  >>> RPDS.10.03.00-02-0250/16  >>> Cyfrowy zawrót głowy  >>> "ARGOS" AGNIESZKA SALM  >>> 7281135007NEWLINE
RPDS  >>> RPDS.10.03.00-02-0253/16  >>> Po nITce do kłębka  >>> JERZY ŻEMŁA WROCOMP SZKOLENIA - USŁUGI INFORMATYCZNE  >>> 7491979734NEWLINE
RPDS  >>> RPDS.10.03.00-02-0254/16  >>> ICT. Damy radę!!!  >>> STOWARZYSZENIE EURO-CONCRET  >>> 8942753436NEWLINE
RPDS  >>> RPDS.10.03.00-02-0255/16  >>> Komputer Twoją szansą!  >>> STOWARZYSZENIE AKTYWNEGO WSPIERANIA GOSPODARKI  >>> 8992670534NEWLINE
RPDS  >>> RPDS.10.03.00-02-0257/16  >>> Sterownik 2016  >>> FUNDACJA "EUDAJMONIA"  >>> 8982116523NEWLINE
RPMA  >>> RPMA.09.02.02-14-8134/17  >>> Profilaktyka cukrzycy w Radomiu i gminach Wolanów, Zakrzew i Przytyk  >>> EUROPEJSKIE CENTRUM SZKOLEŃ SP. ZO.O.  >>> 5242776770NEWLINE
RPMA  >>> RPMA.09.02.02-14-8143/17  >>> „Instytut wiedzy - NZOZ Medical Center”  >>> RENATA BLUKACZ JUSTYNA GRZYWACZ SPÓŁKA CYWILNĄ MEDICAL OFFICE  >>> 9521929482NEWLINE
RPMA  >>> RPMA.09.02.02-14-8145/17  >>> Mazowsze kontra cukrzyca  >>> CENTRUM INNOWACJI I SPOŁECZNEJ EKONOMII  >>> 7010424952NEWLINE
RPMA  >>> RPMA.09.02.02-14-8147/17  >>> Działania edukacyjne i konsultacje diabetologiczne na rzecz poprawy stanu zdrowia mieszkańców województwa mazowieckiego.  >>> MAZOWIECKI SZPITAL BRÓDNOWSKI W WARSZAWIE SPÓŁKA Z OGRANICZONĄ ODPOWIEDZIALNOŚCIĄ  >>> 5241879077NEWLINE
RPMA  >>> RPMA.09.02.02-14-8565/17  >>> Terapia zdrowia psychicznego osób z powiatu płockiego i gostynińskiego.  >>> VIDE SP. Z O.O.  >>> 7743211904NEWLINE
RPMA  >>> RPMA.09.02.02-14-8569/17  >>> Przeciwdziałanie depresji  >>> INSTYTUT ROZWOJU OSOBISTEGO SP.Z O.O.  >>> 5272700398NEWLINE
RPMA  >>> RPMA.09.02.02-14-8570/17  >>> "W Centrum harmonii ze światem". Wsparcie deinstytucjonalizacji opieki nad osobami zależnymi z chorobą psychiczną jako alternatywna forma opieki nad osobami niesamodzielnymi, w tym starszymi z terenu woj. mazowieckiego w Ceranowie.  >>> CENTRUM MEDYCZNO- DIAGNOSTYCZNE SPÓŁKA Z OGRANICZONĄ ODPOWIEDZIALNOŚCIĄ  >>> 8212025575NEWLINE
RPMA  >>> RPMA.09.02.02-14-8571/17  >>> "W Centrum harmonii ze światem". Wsparcie deinstytucjonalizacji opieki nad osobami zależnymi z chorobą psychiczną jako alternatywna forma opieki nad osobami niesamodzielnymi w tym starszymi z terenu woj. mazowieckiego w Żelechowie.  >>> "CENTRUM MEDYCZNO- DIAGNOSTYCZNE" SPÓŁKA Z OGRANICZONĄ ODPOWIEDZIALNOŚCIĄ  >>> 8212025575NEWLINE
RPMA  >>> RPMA.09.02.02-14-8572/17  >>> "W Centrum harmonii ze światem". Wsparcie deinstytucjonalizacji opieki nad osobami zależnymi z chorobą psychiczną jako alternatywna forma opieki nad osobami niesamodzielnymi w tym starszymi z terenu woj. mazowieckiego w Siedlcach.  >>> "CENTRUM MEDYCZNO- DIAGNOSTYCZNE" SPÓŁKA Z OGRANICZONĄ ODPOWIEDZIALNOŚCIĄ  >>> 8212025575NEWLINE
RPMA  >>> RPMA.09.02.02-14-8573/17  >>> "W Centrum harmonii ze światem". Wsparcie deinstytucjonalizacji opieki nad osobami zależnymi z chorobą psychiczną jako alternatywna forma opieki nad osobami niesamodzielnymi w tym starszymi z terenu woj. mazowieckiego w Mińsku Mazowieckim.  >>> "CENTRUM MEDYCZNO- DIAGNOSTYCZNE" SPÓŁKA Z OGRANICZONĄ ODPOWIEDZIALNOŚCIĄ  >>> 8212025575NEWLINE
RPMA  >>> RPMA.09.02.02-14-8574/17  >>> "W Centrum harmonii ze światem". Wsparcie deinstytucjonalizacji opieki nad osobami zależnymi z chorobą psychiczną jako alternatywna forma opieki nad osobami niesamodzielnymi w tym starszymi z terenu woj. mazowieckiego w Oleśnicy.  >>> CENTRUM MEDYCZNO- DIAGNOSTYCZNE SPÓŁKA Z OGRANICZONĄ ODPOWIEDZIALNOŚCIĄ  >>> 8212025575NEWLINE
RPMA  >>> RPMA.09.02.02-14-8805/17  >>> Skuteczna diagnoza i indywidualna terapia w środowisku domowym szansą dla dzieci z autyzmem z województwa mazowieckiego  >>> MAZOWIECKIE CENTRUM NEUROPSYCHIATRII SP. Z O. O.  >>> 5322002036NEWLINE
RPMA  >>> RPMA.09.02.02-14-8807/17  >>> Kompleksowe wsparcie dla dzieci ze spektrum autyzmu  >>> PULMO SP Z O.O.  >>> 5242770885NEWLINE
RPMA  >>> RPMA.09.02.02-14-8809/17  >>> Mazowsze otwiera serce i świat dla dzieci z autyzmem  >>> CENTRUM INNOWACJI I SPOŁECZNEJ EKONOMII  >>> 7010424952NEWLINE
RPMA  >>> RPMA.09.02.02-14-8810/17  >>> Praca z dzieckiem z zaburzeniami autyzmu na Mazowszu  >>> POTRIMPUS WITOLD RYTWIŃSKI  >>> 5291805684NEWLINE
RPMA  >>> RPMA.09.02.02-14-8811/17  >>> Poprawa pracy z dzieckiem z zaburzeniami autyzmu  >>> ZAKŁAD USŁUGOWY "J.P." JAROSŁAW PAĆKO  >>> 5291236795NEWLINE
RPMA  >>> RPMA.09.02.02-14-8821/17  >>> Badania przesiewowe słuchu uczniów klas I szkół podstawowych na terenie powiatu lipskiego w roku szkolnym 2017/2018 oraz 2018/2019  >>> INSTYTUT FIZJOLOGII I PATOLOGII SŁUCHU  >>> 5261744423NEWLINE
RPMA  >>> RPMA.09.02.02-14-8822/17  >>> Badania przesiewowe słuchu uczniów klas I szkół podstawowych na terenie powiatu szydłowieckiego w roku szkolnym 2017/2018 oraz 2018/2019  >>> INSTYTUT FIZJOLOGII I PATOLOGII SŁUCHU  >>> 5261744423NEWLINE
RPMA  >>> RPMA.09.02.02-14-8823/17  >>> Badania przesiewowe słuchu uczniów klas I szkół podstawowych na terenie powiatu żuromińskiego w roku szkolnym 2017/2018 oraz 2018/2019  >>> INSTYTUT FIZJOLOGII I PATOLOGII SŁUCHU  >>> 5261744423NEWLINE
POIS  >>> POIS.01.02.00-00-0001/16  >>> Termomodernizacja budynku stacji kontroli pojazdów i budynku administracyjnego Kaliskich Linii Autobusowych sp. z o.o. w Kaliszu  >>> KALISKIE LINIE AUTOBUSOWE SP. Z O.O.  >>> 6180033902NEWLINE
POIS  >>> POIS.01.02.00-00-0002/18  >>> Poprawa efektywności energetycznej w zakładach NM Polska Sp. z o.o. w Namysłowie poprzez modernizację oświetlenia  >>> NM POLSKA SP. Z O.O.  >>> 7521457964NEWLINE
POIS  >>> POIS.01.02.00-00-0003/17  >>> Kompleksowa głęboka modernizacja energetyczna budynków należących do Miejskiego Przedsiębiorstwa Komunikacji Sp. z o.o. w Kielcach  >>> MIEJSKIE PRZEDSIĘBIORSTWO KOMUNIKACJI W KIELCACH SP. Z.O.O.  >>> 9591503630NEWLINE
POIS  >>> POIS.01.02.00-00-0003/18  >>> Poprawa efektywności energetycznej w zakładach NB Polska Sp. z o.o. w Gnieźnie ul. Słoneczna 29 poprzez modernizację oświetlenia  >>> NB POLSKA SP. Z O.O.  >>> 5211501173NEWLINE
POIS  >>> POIS.01.02.00-00-0004/18  >>> Poprawa efektywności energetycznej w zakładach NB Polska Sp. z o.o. w Gnieźnie ul. Kolejowa 7 poprzez modernizację oświetlenia  >>> NB POLSKA SP. Z O.O.  >>> 5211501173NEWLINE
POIS  >>> POIS.01.02.00-00-0005/17  >>> Głęboka termomodernizacja budynku biurowego w Poznaniu  >>> SHIRAZ SPÓŁKA Z OGRANICZONĄ ODPOWIEDZIALNOŚCIĄ SPÓŁKA KOMANDYTOWO - AKCYJNA  >>> 7820020614NEWLINE
POIS  >>> POIS.01.02.00-00-0007/16  >>> Modernizacja oświetlenia placu parkingowego STS Automotive Sp. z o. o.  >>> STS AUTOMOTIVE SPÓŁKA Z OGRANICZONĄ ODPOWIEDZIALNOŚCIĄ  >>> 5252384712NEWLINE
POIS  >>> POIS.01.02.00-00-0007/18  >>> Termomodernizacja budynków hal przemysłowych przy ul. Fabrycznej 10 we Wrocławiu  >>> DOLNOŚLĄSKIE ZAKŁADY USŁUGOWO-PRODUKCYJNE "DOZAMEL" SP. Z O.O.  >>> 8960001014NEWLINE
POIS  >>> POIS.01.02.00-00-0008/16  >>> Modernizacja oświetlenia hali magazynowej CLIP V w miejscowości Jasin  >>> CENTRUM LOGISTYCZNO INWESTYCYJNE POZNAŃ V SP.Z O.O.  >>> 7772864477NEWLINE
POIS  >>> POIS.01.02.00-00-0008/18  >>> Modernizacja układu pomp wody sieciowej typu 35B63 w PGE GiEK S.A. Oddział Elektrociepłownia Kielce  >>> PGE ENERGIA CIEPŁA SPÓŁKA AKCYJNA  >>> 6420000642NEWLINE
POIS  >>> POIS.01.02.00-00-0009/18  >>> Poprawa efektywności energetycznej w JSW KOKS S.A.  >>> JSW KOKS SPÓŁKA AKCYJNA  >>> 6292256576NEWLINE
POIS  >>> POIS.01.02.00-00-0010/18  >>> Poprawa efektywności energetycznej wytwarzania energii elektrycznej i ciepła poprzez modernizację pomp wody chłodzącej w Enea Połaniec S.A.  >>> ENEA ELEKTROWNIA POŁANIEC SPÓŁKA AKCYJNA  >>> 8660001429NEWLINE
POIS  >>> POIS.01.02.00-00-0011/18  >>> Poprawa efektywności energetycznej budynków przedsiębiorstwa Zakłady Naprawcze Taboru Kolejowego Mińsk Mazowiecki S.A. poprzez wymianę opraw oświetleniowych wraz z osprzętem na energooszczędne oraz wdrożenie inteligentnych systemów sterowania oświetleniem  >>> ZAKŁADY NAPRAWCZE TABORU KOLEJOWEGO MIŃSK MAZOWIECKI SPÓŁKA AKCYJNA  >>> 8220003803NEWLINE
POIS  >>> POIS.01.02.00-00-0013/18  >>> Poprawa efektywności energetycznej poprzez wymianę oświetlenia na energooszczędne typu LED na parkingach Kraków Airport  >>> MIĘDZYNARODOWY PORT LOTNICZY IM. JANA PAWŁA II KRAKÓW-BALICE SP. Z O.O.  >>> 6761336952NEWLINE
POIS  >>> POIS.01.02.00-00-0014/18  >>> Termomodernizacja zasilenia w energię cieplną technologii produkcji mas bitumicznych i emulsji asfaltowych  >>> PRZEDSIĘBIORSTWO ROBÓT DROGOWYCH LUBARTÓW SPÓŁKA AKCYJNA  >>> 7141627101NEWLINE
POIS  >>> POIS.01.02.00-00-0019/18  >>> Modernizacja energetyczna zakładu przemysłowego Forest Gorlice Sp. z o. o.  >>> FOREST GORLICE SPÓŁKA Z OGRANICZONĄ ODPOWIEDZIALNOŚCIĄ  >>> 7381875324NEWLINE
POIS  >>> POIS.01.02.00-00-0021/18  >>> Poprawa efektywności energetycznej spółki Mostostal Kielce S.A. przez termomodernizację oraz modernizację oświetlenia  >>> MOSTOSTAL KIELCE S.A.  >>> 6570242329NEWLINE
POIS  >>> POIS.01.03.01-00-0001/17  >>> Termomodernizacja budynków Państwowej Straży Pożarnej na terenie województwa mazowieckiego  >>> KOMENDA WOJEWÓDZKA PAŃSTWOWEJ STRAŻY POŻARNEJ W WARSZAWIE  >>> 5261796733NEWLINE
POIS  >>> POIS.01.03.01-00-0001/18  >>> Termomodernizacja budynku Ministerstwa Inwestycji i Rozwoju przy ul. Wspólnej 2/4 w Warszawie  >>> MINISTERSTWO INWESTYCJI I ROZWOJU  >>> 5262895199NEWLINE
POIS  >>> POIS.01.03.01-00-0002/16  >>> Termomodernizacja budynku głównego Państwowej Wyższej Szkoły Zawodowej w Lesznie  >>> PAŃSTWOWA WYŻSZA SZKOŁA  >>> 6971981908NEWLINE
POIS  >>> POIS.01.03.01-00-0002/17  >>> Modernizacja energetyczna Pałacu Krasińskich (Pałacu Rzeczypospolitej) przy Placu Krasińskich 3/5 w Warszawie  >>> BIBLIOTEKA NARODOWA  >>> 5261667036NEWLINE
POIS  >>> POIS.01.03.01-00-0003/16  >>> Przebudowa i rozbudowa budynku przy ul. Narutowicza 32, 32b dla potrzeb Prokuratury Rejonowej Lublin – Północ w Lublinie  >>> PROKURATURA OKRĘGOWA W LUBLINIE  >>> 7122291114NEWLINE
POIS  >>> POIS.01.03.01-00-0003/17  >>> Głęboka Termomodernizacja Obiektów Instytutu Lotnictwa.  >>> INSTYTUT LOTNICTWA  >>> 5250008494NEWLINE
POIS  >>> POIS.01.03.01-00-0004/16  >>> Kompleksowa termomodernizacja Aresztu Śledczego w Tarnowskich Górach, przy ulicy Opolskiej 17a wraz z modernizacją instalacji wewnętrznych oraz instalacją fotowoltaiczną, etap I - budynek B.  >>> ARESZT ŚLEDCZY W TARNOWSKICH GÓRACH  >>> 6451115599NEWLINE
POIS  >>> POIS.01.03.01-00-0004/17  >>> Kompleksowa modernizacja energetyczna budynków Instytutu Biopolimerów i Włókien Chemicznych w celu zwiększenia efektywności energetycznej  >>> INSTYTUT BIOPOLIMERÓW I WŁÓKIEN CHEMICZNYCH  >>> 7240000138NEWLINE
POIS  >>> POIS.01.03.01-00-0005/16  >>> Termomodernizacja budynków dydaktyczno-administracyjnych UJK przy ul. Żeromskiego 5 w Kielcach  >>> UNIWERSYTET JANA KOCHANOWSKIEGO W KIELCACH  >>> 6570234850NEWLINE
POIS  >>> POIS.01.03.01-00-0005/17  >>> Kompleksowa termomodernizacja strażnic Komendy Wojewódzkiej Państwowej Straży Pożarnej w Łodzi zlokalizowanych w Łęczycy i Skierniewicach  >>> KOMENDA WOJEWÓDZKA PAŃSTWOWEJ STRAŻY POŻARNEJ W ŁODZI  >>> 7270134501NEWLINE
POIS  >>> POIS.01.03.01-00-0006/16  >>> Termomodernizacja obiektów dydaktyczno-naukowych Uniwersytetu Przyrodniczego we Wrocławiu  >>> UNIWERSYTET PRZYRODNICZY WE WROCŁAWIU  >>> 8960005354NEWLINE
POIS  >>> POIS.01.03.01-00-0006/17  >>> Termomodernizacja infrastruktury naukowo-dydaktycznej Uniwersytetu Medycznego w Białymstoku – budynków przy ul. Wołodyjowskiego 1 i Mieszka I 4 b  >>> UNIWERSYTET MEDYCZNY W BIAŁYMSTOKU  >>> 5420211717NEWLINE
POIS  >>> POIS.01.03.01-00-0007/16  >>> Termomodernizacja budynków (3.1 i 3.2) Uniwersytetu Technologiczno-Przyrodniczego wraz z wymianą oświetlenia wewnętrznego.  >>> UNIWERSYTET TECHNOLOGICZNO-PRZYRODNICZY IM. JANA I JĘDRZEJA ŚNIADECKICH W BYDGOSZCZY  >>> 5540313107NEWLINE
POIS  >>> POIS.01.03.01-00-0007/17  >>> Głęboka modernizacja budynku Filii Krajowej Szkoły Skarbowości w Muszynie  >>> KRAJOWA SZKOŁA SKARBOWOŚCI  >>> 1132932391NEWLINE
POIS  >>> POIS.01.03.01-00-0008/16  >>> Zwiększenie efektywności energetycznej budynków Skarbu Państwa poprzez wykonanie ich głębokiej, kompleksowej modernizacji energetycznej  >>> AGENCJA BEZPIECZEŃSTWA WEWNĘTRZNEGO  >>> 5213199092NEWLINE
POIS  >>> POIS.01.03.01-00-0008/17  >>> Zwiększenie efektywności energetycznej budynku Instytutu Hematologii i Transfuzjologii przy ul. Indiry Gandhi 14.  >>> INSTYTUT HEMATOLOGII I TRANSFUZJOLOGII  >>> 5250009424NEWLINE
POIS  >>> POIS.01.03.01-00-0009/16  >>> Zwiększenie standardu energetycznego budynków UMCS w Lublinie poprzez optymalizację zużycia energii elektrycznej i cieplnej oraz redukcję CO2  >>> UNIWERSYTET MARII CURIE-SKŁODOWSKIEJ  >>> 7120103692NEWLINE
POIS  >>> POIS.01.03.01-00-0009/17  >>> Poprawa efektywności energetycznej wybranych budynków WAT  >>> WOJSKOWA AKADEMIA TECHNICZNA IM. JAROSŁAWA DĄBROWSKIEGO  >>> 5270206300NEWLINE
POIS  >>> POIS.01.03.01-00-0010/16  >>> Termomodernizacja sześciu budynków dydaktycznych Politechniki Śląskiej  >>> POLITECHNIKA ŚLĄSKA  >>> 6310200736NEWLINE
POIS  >>> POIS.01.03.01-00-0010/17  >>> Termomodernizacja budynków szkoły, internatu i warsztatów szkolnych przy Zespole Szkół Centrum Kształcenia Rolniczego w Sejnach.  >>> ZESPÓŁ SZKÓŁ CENTRUM KSZTAŁCENIA ROLNICZEGO IM. ST. STASZICA W SEJNACH  >>> 8441259754NEWLINE
POIS  >>> POIS.01.03.01-00-0011/16  >>> Termomodernizacja budynku przy ul. Chodkiewicza 32 na potrzeby Komendy Miejskiej Policji w Bydgoszczy  >>> KOMENDA WOJEWÓDZKA POLICJI W BYDGOSZCZY  >>> 5540312993NEWLINE
POIS  >>> POIS.01.03.01-00-0011/17  >>> Głęboka termomodernizacja budynków szkolnych w Zespole Szkół Centrum Kształcenia Rolniczego w Marianowie  >>> ZESPÓŁ SZKÓŁ CENTRUM KSZTAŁCENIA ROLNICZEGO IM. CHOR. JANA SZYMAŃSKIEGO W MARIANOWIE  >>> 7181103485NEWLINE
POIS  >>> POIS.01.03.01-00-0012/16  >>> Termomodernizacja budynku E Komendy Miejskiej Policji we Włocławku  >>> KOMENDA WOJEWÓDZKA POLICJI W BYDGOSZCZY  >>> 5540312993NEWLINE
POIS  >>> POIS.01.03.01-00-0012/17  >>> Kompleksowa modernizacja energetyczna budynku Urzędu Skarbowego w Strzyżowie  >>> IZBA ADMINISTRACJI SKARBOWEJ W RZESZOWIE  >>> 8131096298NEWLINE
POIS  >>> POIS.01.03.01-00-0013/16  >>> Termomodernizacja budynków zaplecza technicznego Komendy Wojewódzkiej Policji w Bydgoszczy przy ul. Iławskiej 1  >>> SKARB PAŃSTWA - KOMENDANT WOJEWÓDZKI POLICJI W BYDGOSZCZY  >>> 5540312993NEWLINE
POIS  >>> POIS.01.03.01-00-0013/17  >>> Termomodernizacja budynków Warmińsko-Mazurskiego Wojewódzkiego Inspektoratu Ochrony Środowiska przy ul. Osińskiego 12/13 w Olsztynie i przy ul. Powstańców Warszawskich 10 w Elblągu  >>> WARMIŃSKO-MAZURSKI WOJEWÓDZKI INSPEKTOR OCHRONY ŚRODOWISKA W OLSZTYNIE  >>> 7391146816NEWLINE
POIS  >>> POIS.01.03.01-00-0014/16  >>> Wzmocnienie efektywności energetycznej obiektów służbowych Pomorskiej policji poprzez ich kompleksową termomodernizację  >>> KOMENDA WOJEWÓDZKA POLICJI W GDAŃSKU  >>> 5830010088NEWLINE
POIS  >>> POIS.01.03.01-00-0014/17  >>> Poprawa efektywności energetycznej budynków Izby Administracji Skarbowej województwa lubelskiego – 3 budynki, II edycja  >>> IZBA ADMINISTRACJI SKARBOWEJ W LUBLINIE  >>> 7121067254NEWLINE
POIS  >>> POIS.01.03.01-00-0015/17  >>> Termomodernizacja budynków Wydziału Mechanicznego Politechniki Krakowskiej, Laboratoria J (1A) i K (1B), al. Jana Pawła II 37, Kraków”  >>> POLITECHNIKA KRAKOWSKA IM. TADEUSZA KOŚCIUSZKI  >>> 6750006257NEWLINE
POIS  >>> POIS.01.03.01-00-0016/16  >>> Termomodernizacja budynku Lubuskiego Urzędu Wojewódzkiego w Gorzowie Wlkp  >>> LUBUSKI URZĄD WOJEWÓDZKI W GORZOWIE WIELKOPOLSKIM  >>> 5992462314NEWLINE\n"""

def create_projects(apps, schema_editor):
    Project = apps.get_model('kontrolBack', 'Project')
    records = [inner.split(' >>> ') for inner in PROJECTS_STRING.split('NEWLINE\n')][:-1]
    projects = [Project(
        programme=r[0], code=r[1], name=r[2], beneficiary_name=r[3], beneficiary_nip=r[4]
        ) for r in records]  
    Project.objects.bulk_create(projects)

class Migration(migrations.Migration):

    dependencies = [
        ('kontrolBack', '0003_auto_20200123_2046'),
    ]

    operations = [
        migrations.RunPython(create_projects)
    ]
