# Generated by Django 2.2.7 on 2020-01-24 21:29

from django.db import migrations

BLOCKS = [
    '01 Realizacja projektu',
    '02 Realizacja kontraktów',
    '03 Dokumentacja finansowa',
    '03 Koszty personelu',
    '03 Wskaźniki', 
    '04 Informacja i promocja',
    '05 Ochrona danych osobowych',
    '99 Inne'
]

def create_blocks(apps, schema_editor):
    Block = apps.get_model('kontrolBack', 'QuestionBlock')
    blocks = [Block(name=b) for b in BLOCKS]  
    Block.objects.bulk_create(blocks)


class Migration(migrations.Migration):

    dependencies = [
        ('kontrolBack', '0005_institution_is_coordinator'),
    ]

    operations = [
        migrations.RunPython(create_blocks)
    ]
