# Generated by Django 2.2.7 on 2020-01-26 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kontrolBack', '0008_auto_20200125_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='comment',
            field=models.CharField(default=True, max_length=10000, null=True),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
