# Generated by Django 2.2.7 on 2020-01-26 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kontrolBack', '0011_auto_20200126_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='kontrolBack.QuestionInControl'),
        ),
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together=set(),
        ),
    ]
